/ ignore

l seek +5
right seek +5
L seek +8
Shift+right seek +8
h seek -5
left seek -5
H seek -8
Shift+left seek -8
j seek +30
down seek +30
J seek +45
Shift+down seek +45
k seek -30
up seek -30
K seek -45
Shift+up seek -45
t cycle sub
T cycle sub down
´ ab-loop
q quit-watch-later
Q quit
< script-binding prev-or-start
? script-binding jump-to-random
+ script-binding decode-qr
* script-binding decode-qr-to-clipboard