name: "main_bar"
position: "top"
height: 0
popup_gap: 6
popup_autohide: false
start:
  - type: "custom"
    class: "widget-box"
    bar:
    - type: "workspaces"
      all_monitors: true
      sort: "index"
    - type: "label"
      name: "dummy-widget-gradient"
      label: ""
  - type: "bindmode"
center:
  - type: "focused"
    icon_size: 18
    truncate: "middle"
    show_title: true
end:
  - type: "custom"
    name: "clipboard"
    bar:
    - type: "button"
      on_click: "!$HOME/.config/ironbar/scripts/wl-clipboard widget main_bar clipboard"
      widgets:
      - type: "label"
        label: " "
      - type: "label"
        name: "clipboard-contents"
        label: "{{watch:$HOME/.config/ironbar/scripts/wl-clipboard}}"
    popup:
    - type: "box"
      orientation: "vertical"
      class: "clipboard-popup"
      widgets:
      - type: "button"
        class: "text-button"
        show_if: "#clip2"
        label: "#clip2"
        on_click: "!$HOME/.config/ironbar/scripts/wl-clipboard varcopy 2"
      - type: "button"
        class: "text-button"
        show_if: "#clip3"
        label: "#clip3"
        on_click: "!$HOME/.config/ironbar/scripts/wl-clipboard varcopy 3"
      - type: "button"
        class: "text-button"
        show_if: "#clip4"
        label: "#clip4"
        on_click: "!$HOME/.config/ironbar/scripts/wl-clipboard varcopy 4"
      - type: "button"
        class: "text-button"
        show_if: "#clip5"
        label: "#clip5"
        on_click: "!$HOME/.config/ironbar/scripts/wl-clipboard varcopy 5"
      - type: "button"
        class: "text-button"
        show_if: "#clip6"
        label: "#clip6"
        on_click: "!$HOME/.config/ironbar/scripts/wl-clipboard varcopy 6"
  - type: "music"
    player_type: "mpd"
    music_dir: "$HOME/Musik/"
    marquee:
      enable: true
      max_length: 40
      pause_duration: 10000
  - type: "script"
    cmd: "$HOME/.config/ironbar/scripts/network eno1 wlan0"
    mode: "poll"
    interval: 10000
  - type: "bluetooth"
    format:
      disabled: ""
      enabled: ""
  - type: "inhibit"
    durations: ["00:30:00", "01:00:00", "inf"]
    format_on: ' {duration}'
    format_off: ''
  - type: "clock"
    name: "clock"
    format: " %H:%M"
  - type: "tray"
