#!/bin/bash

swayidle_pid=

if [ "$BLOCK_BUTTON" = 1 ]; then
    swayidle_pid=$(pgrep -x swayidle)

    if [ -n "$swayidle_pid" ]; then
        kill "$swayidle_pid"
        notify-send "   Caffeine enabled" "Screen will not turn off on idle"
    else
        nohup swayidle > /dev/null 2>&1 &
        notify-send "   Caffeine disabled" "Screen will not off on idle"
    fi
fi

swayidle_pid=$(pgrep -x swayidle)

if [ -z "$swayidle_pid" ]; then
    echo ""
else
    echo ""
fi
