#!/bin/bash

if [ -z "$CLIPBOARD_STATE" ]; then
    test -z "$WAYLAND_DISPLAY" && exit
    script_loc=$(dirname -- "$( readlink -f -- "$0"; )";)/$(basename "$0")
    wl-paste --watch "$script_loc"
else
    clip_content="$(cat | tr -dc '[:graph]' | tr -d \&\'\"\<\>)"
    if [[ -z "$clip_content" ]]; then
         stdbuf -oL echo ""
         exit
    fi
       
    test  "$CLIPBOARD_STATE" = "sensitive" && clip_content=$(echo -n "$clip_content" | tr "[:graph:]" "*")
    test ${#clip_content} -gt 15 && clip_content="${clip_content:0:15}…"
    stdbuf -oL echo " <span font_size='small'>$clip_content</span>"
fi
