#
# Overrides for /etc/makepkg.conf
#
# changes from defaults: !debug !lto
OPTIONS=(strip docs !libtool !staticlibs emptydirs zipman purge !debug !lto)

#-- Make Flags: change this for DistCC/SMP systems
MAKEFLAGS="-j4"

#-- Destination: specify a fixed directory where all packages will be placed
PKGDEST=/var/cache/pacman/makepkg

# vim: set ft=sh ts=2 sw=2 et:
