#!/bin/bash

WIRED_INSTANCE=${1}
WIFI_INSTANCE=${2}

html_escape() {
    sed 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g; s/"/\&quot;/g; s/'"'"'/\&#39;/g'
}

# wired connection
if [[ -n $WIRED_INSTANCE ]]; then
    STATE=$(cat "/sys/class/net/${WIRED_INSTANCE}/operstate")

    if [[ $STATE == "up" ]]; then
        if ip route | grep -q "${WIRED_INSTANCE}" ; then
            wired="<span weight='bold'>󰌹</span>"
        else
            wired="󰌺"
        fi
    fi
fi

# wifi connection
if [[ -n $WIFI_INSTANCE ]]; then
    if [ $(($(cat "/sys/class/net/${WIFI_INSTANCE}/flags") & 0x1)) -eq 0 ]; then
        wifi=''
    else
        QUALITY=$(grep "$WIFI_INSTANCE" /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')
        WIFI_SSID=$(iwctl station "$WIFI_INSTANCE" show | perl -ne 'print if s/^\s*Connected network\s*(.+?)\s*$/\1/' | html_escape)

        if [[ -z "$WIFI_SSID" ]]; then
            wifi="󰤮"
        elif [[ $QUALITY -ge 80 ]]; then
            wifi="<span weight='bold>󰤨</span>"
        elif [[ $QUALITY -ge 60 ]]; then
            wifi="<span weight='bold>󰤥</span>"
        elif [[ $QUALITY -ge 40 ]]; then
            wifi="<span weight='bold>󰤢</span>"
        else
            wifi="<span weight='bold>󰤟</span>"
        fi
    fi
fi

echo "${wired}${wifi:+${wired:+ }$wifi${WIFI_SSID:+ <span size='small'>${WIFI_SSID}</span>}}${vpn:+ }$vpn"
