#!/bin/bash
test -z "$WAYLAND_DISPLAY" && exit

CACHE_FILE="${HOME}/.cache/ironbar/clip_cache"

function setup_clip_cache {
    mkdir -p "$(dirname "$CACHE_FILE")"
    touch "$CACHE_FILE"
}

function write_to_cache {
    declare -a cache_content
    cache_content=("$1")
    if grep -Fxq -- "${cache_content[0]}" "$CACHE_FILE"; then
        return
    fi
    while IFS= read -r line; do cache_content+=("$line"); done < <(head -n5 "$CACHE_FILE")
    printf "%s\n" "${cache_content[@]}" > "$CACHE_FILE"
}

function init_script {
    setup_clip_cache

    script_loc=$(dirname -- "$( readlink -f -- "$0"; )";)/$(basename "$0")
    # kill all already running wl-paste commands launched from this script
    pkill -f -- "wl-paste --watch $script_loc"
    wl-paste --watch "$script_loc"
}

function update_ironvars {
    test -f "$CACHE_FILE" || exit 1
    counter=2
    while read -r line; do
        test ${#line} -gt 30 && line="${line:0:30}…"
        ironbar var set -- "clip${counter}" "$line" >/dev/null 
        ((counter++))
    done < <(tail -n +2 "$CACHE_FILE")
}

function cp_from_ironvars {
    test -f "$CACHE_FILE" || exit 1
    sed -n "${1}p" "$CACHE_FILE" | wl-copy
}

function widget_click {
    local bar_name="$1"
    local widget_name="$2"

    if [ "$(ironbar bar "$bar_name" get-popup-visible)" = "true" ]; then
        ironbar bar "$bar_name" hide-popup
        return
    fi
    
    echo "$bar_name"
    echo "$widget_name"
    update_ironvars &
    ironbar bar "$bar_name" show-popup "$widget_name"
}

function update_widget {
    clip_content="$(cat | perl -pE 's/[^\p{XPosixPrint}]//g')"
    if [[ -z "$clip_content" || "$clip_content" =~ ^[[:space:]]+$ ]]; then
        stdbuf -oL echo ""
        exit
    fi
    
    if [ "$CLIPBOARD_STATE" = "sensitive" ]; then
        clip_content=$(echo -n "$clip_content" | tr "[:graph:]" "*")
    else
        write_to_cache "$clip_content"
    fi

    clip_content="$(echo -n "$clip_content" | xargs)"
    test ${#clip_content} -gt 15 && clip_content="${clip_content:0:15}…"
    stdbuf -oL echo "$clip_content"
}

if [ -n "$CLIPBOARD_STATE" ]; then
    update_widget
    exit
fi

case "$1" in
    widget)
        widget_click "${@:2}"
        ;;
    varcopy)
        cp_from_ironvars "$2"
        ;;
    *)
        init_script
        ;;
esac
