#!/bin/bash

type () {
    if [[ -n "$WAYLAND_DISPLAY" ]]; then
        which wtype >/dev/null 2>&1 || { notify-send "wtype not installed"; exit 1; }
        wtype -- "$@"
    else
        which xdotool >/dev/null 2>&1 || { notify-send "xdotool not installed"; exit 1; }
        xdotool --clearmodifiers "$@"
    fi
}

if [[ -z "$PASSWORD_STORE_PASS_COTP" ]]; then
    notify-send "\$PASSWORD_STORE_PASS_COTP not set!"
    exit 1
fi

cotp_db=`pass show random/cotp | cotp --password-stdin list -e`

sel=`echo $cotp_db | jq -r '.[] | .["issuer"]' | dmenu`
type `echo $cotp_db | jq -r '.[] | select(.issuer == "'$sel'") |.otp_code'`
